### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SunDionel** [PathwayAndDataAnalysis/mutex#2]
Hello,

**My parameters file:**
data-file	=	mutex.txt
network-file	=	Network.sif
search-on-signaling-network	=	false

**I get the following error:**
Number of genes = 3089
Number of samples = 165

| Searching for groups of 3089 seeds                                                                 
 Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 159
	at org.cbio.mutex.Group.countOverlapWithCandidate(Group.java:145)
	at org.cbio.mutex.Group.calcPVals1(Group.java:102)
	at org.cbio.mutex.Group.calcScore(Group.java:164)
	at org.cbio.mutex.Group.calcFutureScore(Group.java:192)
	at org.cbio.mutex.MutexGreedySearcher.expandGroup(MutexGreedySearcher.java:267)
	at org.cbio.mutex.MutexGreedySearcher.calcGeneVal(MutexGreedySearcher.java:167)
	at org.cbio.mutex.MutexGreedySearcher.getNullDist(MutexGreedySearcher.java:203)
	at org.cbio.mutex.MutexGreedySearcher.assignNullScoreDistr(MutexGreedySearcher.java:184)
	at org.cbio.mutex.MutexGreedySearcher.expandGroup(MutexGreedySearcher.java:246)
	at org.cbio.mutex.MutexGreedySearcher.getGroupOfSeed(MutexGreedySearcher.java:90)
	at org.cbio.mutex.MutexGreedySearcher.getGroupsOfSeeds(MutexGreedySearcher.java:72)
	at org.cbio.mutex.Main.search(Main.java:230)
	at org.cbio.mutex.Main.main(Main.java:147)

**Comment by ozgunbabur** [comment]
It is most likely that there is a problem in your data file mutex.txt. Please check if all the rows have the same number of columns. I can also help if you don't mind sharing the matrix.
